goals.scored.by.team <- 
  plot_ly(gsbt.data, type = 'box') %>%
  add_boxplot(y = ~Arsenal, name = 'Arsenal', 
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(239, 1, 7)',
                            outliercolor = 'rgb(239, 1, 7)',
                            line = list(outliercolor = 'rgb(239, 1, 7)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(239, 1, 7)'),
              fillcolor = list(color = 'rgb(239, 1, 7)')) %>%
  add_boxplot(y = ~AstonVilla, name = 'Aston Villa',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(149,191,229)',
                            outliercolor = 'rgb(149,191,229)',
                            line = list(outliercolor = 'rgb(149,191,229)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(149,191,229)'),
              fillcolor = list(color = 'rgb(149,191,229)')) %>%
  add_boxplot(y = ~Bournemouth, name = 'Bournemouth',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(181, 14, 18)',
                            outliercolor = 'rgb(181, 14, 18)',
                            line = list(outliercolor = 'rgb(181, 14, 18)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(181, 14, 18)'),
              fillcolor = list(color = 'rgb(181, 14, 18)')) %>%
  add_boxplot(y = ~Brentford, name = 'Brentford',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(227, 6, 19)',
                            outliercolor = 'rgb(227, 6, 19)',
                            line = list(outliercolor = 'rgb(227, 6, 19)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(227, 6, 19)'),
              fillcolor = list(color = 'rgb(227, 6, 19)')) %>%
  add_boxplot(y = ~Brighton, name = 'Brighton',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(0, 87, 184)',
                            outliercolor = 'rgb(0, 87, 184)',
                            line = list(outliercolor = 'rgb(0, 87, 184)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(0, 87, 184)'),
              fillcolor = list(color = 'rgb(0, 87, 184)')) %>%
  add_boxplot(y = ~Burnley, name = 'Burnley',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(108, 29, 69)',
                            outliercolor = 'rgb(108, 29, 69)',
                            line = list(outliercolor = 'rgb(108, 29, 69)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(108, 29, 69)'),
              fillcolor = list(color = 'rgb(108, 29, 69)')) %>%
  add_boxplot(y = ~Chelsea, name = 'Chelsea',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(3, 70, 148)',
                            outliercolor = 'rgb(3, 70, 148)',
                            line = list(outliercolor = 'rgb(3, 70, 148)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(3, 70, 148)'),
              fillcolor = list(color = 'rgb(3, 70, 148)')) %>%
  add_boxplot(y = ~CrystalPalace, name = 'Crystal Palace',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(27, 69, 143)',
                            outliercolor = 'rgb(27, 69, 143)',
                            line = list(outliercolor = 'rgb(27, 69, 143)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(27, 69, 143)'),
              fillcolor = list(color = 'rgb(27, 69, 143)')) %>%
  add_boxplot(y = ~Everton, name = 'Everton',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(39, 68, 136)',
                            outliercolor = 'rgb(39, 68, 136)',
                            line = list(outliercolor = 'rgb(39, 68, 136)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(39, 68, 136)'),
              fillcolor = list(color = 'rgb(39, 68, 136)')) %>%
  add_boxplot(y = ~Fulham, name = 'Fulham',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(0, 0, 0)',
                            outliercolor = 'rgb(0, 0, 0)',
                            line = list(outliercolor = 'rgb(0, 0, 0)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(0, 0, 0)'),
              fillcolor = list(color = 'rgb(0, 0, 0)')) %>%
  # add_boxplot(y = ~Leeds, name = 'Leeds United',
  #             boxpoints = 'suspectedoutliers',
  #             marker = list(color = 'rgb(255, 205, 0)',
  #                           outliercolor = 'rgb(255, 205, 0)',
  #                           line = list(outliercolor = 'rgb(255, 205, 0)',
  #                                       outlierwidth = 2)) ,
  #             line = list(color = 'rgb(255, 205, 0)'),
  #             fillcolor = list(color = 'rgb(255, 205, 0)')) %>%
  # add_boxplot(y = ~Leicester, name = 'Leicester City',
  #             boxpoints = 'suspectedoutliers',
  #             marker = list(color = 'rgb(0, 83, 160)',
  #                           outliercolor = 'rgb(0, 83, 160)',
  #                           line = list(outliercolor = 'rgb(0, 83, 160)',
  #                                       outlierwidth = 2)) ,
  #             line = list(color = 'rgb(0, 83, 160)'),
  #             fillcolor = list(color = 'rgb(0, 83, 160)')) %>%
  add_boxplot(y = ~Liverpool, name = 'Liverpool',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(200, 12, 46)',
                            outliercolor = 'rgb(200, 12, 46)',
                            line = list(outliercolor = 'rgb(200, 12, 46)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(200, 12, 46)'),
              fillcolor = list(color = 'rgb(200, 12, 46)')) %>%
  add_boxplot(y = ~LutonTown, name = 'Luton Town',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(247, 143, 30)',
                            outliercolor = 'rgb(247, 143, 30)',
                            line = list(outliercolor = 'rgb(247, 143, 30)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(247, 143, 30)'),
              fillcolor = list(color = 'rgb(247, 143, 30)')) %>%
  add_boxplot(y = ~ManCity, name = 'Manchester City',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(108, 171, 221)',
                            outliercolor = 'rgb(108, 171, 221)',
                            line = list(outliercolor = 'rgb(108, 171, 221)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(108, 171, 221)'),
              fillcolor = list(color = 'rgb(108, 171, 221)')) %>%
  add_boxplot(y = ~ManUnited, name = 'Manchester United',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(218, 41, 28)',
                            outliercolor = 'rgb(218, 41, 28)',
                            line = list(outliercolor = 'rgb(218, 41, 28)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(218, 41, 28)'),
              fillcolor = list(color = 'rgb(218, 41, 28)')) %>%
  add_boxplot(y = ~Newcastle, name = 'Newcastle',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(45, 41, 38)',
                            outliercolor = 'rgb(45, 41, 38)',
                            line = list(outliercolor = 'rgb(45, 41, 38)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(45, 41, 38)'),
              fillcolor = list(color = 'rgb(45, 41, 38)')) %>%
  # add_boxplot(y = ~Norwich, name = 'Norwich City',
  #             boxpoints = 'suspectedoutliers',
  #             marker = list(color = 'rgb(0, 166, 80)',
  #                           outliercolor = 'rgb(0, 166, 80)',
  #                           line = list(outliercolor = 'rgb(0, 166, 80)',
  #                                       outlierwidth = 2)) ,
  #             line = list(color = 'rgb(0, 166, 80)'),
  #             fillcolor = list(color = 'rgb(0, 166, 80)')) %>%
  add_boxplot(y = ~NottmForest, name = 'Nottingham Forest',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(229, 50, 51)',
                            outliercolor = 'rgb(229, 50, 51)',
                            line = list(outliercolor = 'rgb(229, 50, 51)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(229, 50, 51)'),
              fillcolor = list(color = 'rgb(229, 50, 51)')) %>%
  add_boxplot(y = ~SheffieldUnited, name = 'Sheffield United',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(238,39,55)',
                            outliercolor = 'rgb(238,39,55)',
                            line = list(outliercolor = 'rgb(238,39,55)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(238,39,55)'),
              fillcolor = list(color = 'rgb(238,39,55)')) %>%
  # add_boxplot(y = ~Southampton, name = 'Southampton',
  #             boxpoints = 'suspectedoutliers',
  #             marker = list(color = 'rgb(215, 25, 32)',
  #                           outliercolor = 'rgb(215, 25, 32)',
  #                           line = list(outliercolor = 'rgb(215, 25, 32)',
  #                                       outlierwidth = 2)) ,
  #             line = list(color = 'rgb(215, 25, 32)'),
  #             fillcolor = list(color = 'rgb(215, 25, 32)')) %>%
  add_boxplot(y = ~Tottenham, name = 'Tottenham',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(19, 34, 87)',
                            outliercolor = 'rgb(19, 34, 87)',
                            line = list(outliercolor = 'rgb(19, 34, 87)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(19, 34, 87)'),
              fillcolor = list(color = 'rgb(19, 34, 87)')) %>%
  # add_boxplot(y = ~Watford, name = 'Watford',
  #             boxpoints = 'suspectedoutliers',
  #             marker = list(color = 'rgb(251, 238, 35)',
  #                           outliercolor = 'rgb(251, 238, 35)',
  #                           line = list(outliercolor = 'rgb(251, 238, 35)',
  #                                       outlierwidth = 2)) ,
  #             line = list(color = 'rgb(251, 238, 35)'),
  #             fillcolor = list(color = 'rgb(251, 238, 35)')) %>%
  # add_boxplot(y = ~WestBrom, name = 'West Bromwich Albion',
  #             boxpoints = 'suspectedoutliers',
  #             marker = list(color = 'rgb(18, 47, 103)',
  #                           outliercolor = 'rgb(18, 47, 103)',
  #                           line = list(outliercolor = 'rgb(18, 47, 103)',
  #                                       outlierwidth = 2)) ,
  #             line = list(color = 'rgb(18, 47, 103)'),
  #             fillcolor = list(color = 'rgb(18, 47, 103)')) %>%
  add_boxplot(y = ~WestHam, name = 'West Ham United',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(122, 38, 58)',
                            outliercolor = 'rgb(122, 38, 58)',
                            line = list(outliercolor = 'rgb(122, 38, 58)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(122, 38, 58)'),
              fillcolor = list(color = 'rgb(122, 38, 58)')) %>%
  add_boxplot(y = ~Wolves, name = 'Wolverhampton',
              boxpoints = 'suspectedoutliers',
              marker = list(color = 'rgb(253, 185, 19)',
                            outliercolor = 'rgb(253, 185, 19)',
                            line = list(outliercolor = 'rgb(253, 185, 19)',
                                        outlierwidth = 2)) ,
              line = list(color = 'rgb(253, 185, 19)'),
              fillcolor = list(color = 'rgb(253, 185, 19)')) %>%
  layout(title = paste("Goals Scored by Team <br>", max(rby.data$Year), "-", max(rby.data$Year)+1),
         yaxis = list (title = "Goals Scored", rangemode = 'nonnegative'))

goals.scored.by.team